ARG BUILD_FROM
FROM node:lts-alpine

ENV LANG C.UTF-8

RUN apk add python3 \
&& apk add jq \
&& pip3 install catt

RUN mkdir /assistant_relay \
&& npm i pm2 -g

WORKDIR /assistant_relay

RUN wget https://github.com/greghesp/assistant-relay/releases/download/v3.3.1b/release.zip \
&& unzip release.zip \
&& rm release.zip 

RUN sed -i -e 's#./bin/config.json#/data/config.json#g' /assistant_relay/helpers/server.js \
&& sed -i -e 's#./bin/config.json#/data/config.json#g' /assistant_relay/helpers/assistant.js \
&& sed -i -e 's#./bin/config.json#/data/config.json#g' /assistant_relay/helpers/auth.js \
&& sed -i -e 's#./bin/config.json#/data/config.json#g' /assistant_relay/routes/index.js \
&& sed -i -e 's#./bin/config.json#/data/config.json#g' /assistant_relay/routes/server.js \
&& sed -i -e 's#./bin/config.json#/data/config.json#g' /assistant_relay/routes/cast.js \
&& sed -i -e 's#./bin/config.json#/data/config.json#g' /assistant_relay/routes/server.js \
&& sed -i -e 's#./bin/config.json#/data/config.json#g' /assistant_relay/bin/www \
&& sed -i -e 's#config.json#/data/config.json#g' /assistant_relay/bin/registerDevice.js \
&& sed -i -e 's#../bin/audio-responses/#/data/audio-responses/#g' /assistant_relay/helpers/server.js \
&& sed -i -e 's#../bin/audio-responses/#/data/audio-responses/#g' /assistant_relay/routes/server.js \
&& sed -i -e 's#bin/audio-responses/#/data/audio-responses/#g' /assistant_relay/helpers/server.js

RUN npm i

WORKDIR /
RUN wget https://raw.githubusercontent.com/Apipa169/Assistant-Relay-for-Hassio/master/dockerfiles/amd64-beta/run.sh
RUN chmod a+x /run.sh
CMD [ "/run.sh" ]

ARG BUILD_ARCH
ARG BUILD_DATE
ARG BUILD_REF
ARG BUILD_VERSION

LABEL \
    io.hass.name="Assistant Relay" \
    io.hass.description="Send (broadcast) commands to your Google Assistant via REST command" \
    io.hass.arch="${BUILD_ARCH}" \
    io.hass.type="addon" \
    io.hass.version=${BUILD_VERSION} \
    maintainer="Apipa169" \
    org.label-schema.description="Send (broadcast) commands to your Google Assistant via REST command" \
    org.label-schema.build-date=${BUILD_DATE} \
    org.label-schema.name="Assistant Relay" \
    org.label-schema.usage="https://github.com/Apipa169/Assistant-Relay-for-Hassio/blob/master/README.md" \
    org.label-schema.vcs-ref=${BUILD_REF} \
    org.label-schema.vcs-url="https://github.com/Apipa169/Assistant-Relay-for-Hassio" \